[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
ratatui = { version = "*", features = ["all-widgets"] }
backend = { path = "../backend" }
humansize = "2.1.3"
itertools = "0.11.0"
tokio = { version = "1.37.0", features = ["full"] }
sysinfo = "0.29.10"
